
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvhsdntaskmrvcipybaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aHNkbnRhc2ttcnZjaXB5YmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzA5ODYsImV4cCI6MjA1NjE0Njk4Nn0.MPE094s7bS_kccl-hUCvtO2WwkgeyeQ07bEAl7Slz08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
